# Generated by Django 2.1.2 on 2018-10-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181029_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='cosa',
            field=models.FileField(max_length=50, upload_to=''),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='opt',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
