# Generated by Django 2.1.2 on 2018-10-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181029_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='cosa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datos_personales',
            name='opt',
            field=models.CharField(max_length=50),
        ),
    ]
