# Generated by Django 2.1.2 on 2018-10-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181029_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='correo',
            new_name='edad_aproximada',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='fecha_nacimiento',
            new_name='fecha_rescate',
        ),
        migrations.RemoveField(
            model_name='datos_personales',
            name='cosa',
        ),
        migrations.RemoveField(
            model_name='datos_personales',
            name='opt',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='telefono',
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='blog.Vacuna'),
        ),
    ]
