# Generated by Django 2.1.2 on 2018-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181030_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
