# Generated by Django 2.1.2 on 2018-10-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_mascota_vacuna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='fecha_rescate',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacuna',
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
    ]
