# Generated by Django 2.1.2 on 2018-10-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181030_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacuna',
        ),
    ]
