# Generated by Django 2.1.2 on 2018-10-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_vacuna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='vacuna',
            new_name='raza',
        ),
    ]
