# Generated by Django 2.1.2 on 2018-10-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_mascota_raza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos_personales',
            old_name='fecha_nacimiento',
            new_name='fecha',
        ),
    ]
