# Generated by Django 2.1.2 on 2018-10-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_datos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='edad_aproximada',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='sexo',
            new_name='raza',
        ),
    ]
