# Generated by Django 2.1.2 on 2018-11-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20181105_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
    ]
