# Generated by Django 2.1.2 on 2018-11-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181105_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=models.ImageField(default=5, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
