# Generated by Django 2.1.2 on 2018-11-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_mascota_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='image',
        ),
    ]
