# Generated by Django 2.1.2 on 2018-11-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_mascota_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='image',
            field=models.ImageField(default='Null', upload_to='photos'),
        ),
    ]
