# Generated by Django 2.1.2 on 2018-11-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_mascota_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='image',
            field=models.FileField(upload_to='photos'),
        ),
    ]
