# Generated by Django 2.1.2 on 2018-11-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20181107_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
